CREATE TABLE CLIENTES(
    IdCliente NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    NombreCliente VARCHAR(10) NOT NULL,
    FechaCreacion DATE NOT NULL,
    Estado NUMBER(1,0) NOT NULL,
    PRIMARY KEY(idCliente)
);

CREATE TABLE PRODUCTOS(
    IdProducto NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    NombreProducto VARCHAR2(100) NOT NULL,
    FechaCreacion DATE NOT NULL,
    Estado NUMBER(1,0) NOT NULL,
    PRIMARY KEY(IdProducto)
);

CREATE TABLE PRODUCTOS_CLIENTES(
    IdProductosClientes NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    IdClientes NUMBER(10) NOT NULL,
    IdProductos NUMBER(10) NOT NULL,
    PRIMARY KEY(IdProductosClientes),
    CONSTRAINT fk_clientes_productos FOREIGN KEY(IdClientes) REFERENCES CLIENTES(IdCliente),
    CONSTRAINT fk_productos_clientes FOREIGN KEY(IdProductos) REFERENCES PRODUCTOS(IdProducto)
);

INSERT INTO CLIENTES(NombreCliente,FechaCreacion,Estado) VALUES('Alex',TO_DATE('2021/06/03 14:53:00', 'yyyy/mm/dd hh24:mi:ss'),1);
INSERT INTO CLIENTES(NombreCliente,FechaCreacion,Estado) VALUES('Carlos',TO_DATE('2021/06/03 14:53:00', 'yyyy/mm/dd hh24:mi:ss'),1);

INSERT INTO PRODUCTOS(NombreProducto,FechaCreacion,Estado) VALUES('ERP',TO_DATE('2021/06/03 14:53:00', 'yyyy/mm/dd hh24:mi:ss'),1);
INSERT INTO PRODUCTOS(NombreProducto,FechaCreacion,Estado) VALUES('POS',TO_DATE('2021/06/03 14:53:00', 'yyyy/mm/dd hh24:mi:ss'),1);
INSERT INTO PRODUCTOS(NombreProducto,FechaCreacion,Estado) VALUES('CRM',TO_DATE('2021/06/03 14:53:00', 'yyyy/mm/dd hh24:mi:ss'),0);

INSERT INTO PRODUCTOS_CLIENTES(IdClientes,IdProductos) VALUES(1,1);
INSERT INTO PRODUCTOS_CLIENTES(IdClientes,IdProductos) VALUES(1,2);
INSERT INTO PRODUCTOS_CLIENTES(IdClientes,IdProductos) VALUES(1,3);
INSERT INTO PRODUCTOS_CLIENTES(IdClientes,IdProductos) VALUES(2,1);
INSERT INTO PRODUCTOS_CLIENTES(IdClientes,IdProductos) VALUES(2,3);